version: '3'
services: 
  24hr-deals:
    image: 24hr-deals-api:1
    container_name: 24hr-deals-service
    restart: always
    build: .
    ports: 
      - '5000:5000'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'